version: '3.7'

services:

  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    hostname: mysql-db
    restart: always
    volumes:
      - ./databases:/usr/databases
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"

  mysql-workbench:
    image: linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    hostname: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./databases:/usr/databases
    ports:
      - 3000:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
  
  jupyter:
    image: asami76/allspark:latest
    container_name: jupyter
    hostname: jupyter
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./databases:/home/jovyan/
    ports:
      - 8888:8888
    restart: unless-stopped